// Generated by https://quicktype.io

import { Product } from ".";

export interface Sale {
    id:        number;
    client:    string;
    total:     number;
    createdAt: string;
    details:   Detail[];
}

export interface Detail {
    product: Product;
    amount:  number;
}