// Generated by https://quicktype.io

import { Product } from ".";

export interface Sale {
    id:        number;
    client:    string;
    products:  Product[];
    total:     number;
    createdAt: string;
}

